Dev 1525 make md5 optional
viaacode/s3-events-handler pull request #23
Opened 2021-03-03 18:55 UTC by RudolfDG

2021-03-03 19:27 UTC, maartends requested changes
`import re` missing in `main.py`

```
tests/test_main.py::test_construct_essence_sidecar FAILED
...
FAILED tests/test_main.py::test_construct_essence_sidecar - NameError: name 're' is not defined
```
![Screenshot from 2021-03-03 20-26-36](https://user-images.githubusercontent.com/763374/109860738-c8a5a100-7c5e-11eb-8233-1d4b68381abd.png)

Also, because of time-constraints, adding extra tests can/should become a new issue.

2021-03-05 14:14 UTC, maartends approved these changes

2021-03-08 10:18 UTC, spacid approved these changes

2021-03-08 10:18 UTC, spacid commented on main.py
> +
Perhaps move this to a reusable method as it is used twice?

2021-03-08 10:18 UTC, spacid commented on meemoo/helpers.py
> -    if re.match("^[a-fA-F0-9]{32}$", md5):
Removing this check here results in an unused import of "re".

2021-03-08 10:18 UTC, spacid commented on meemoo/helpers.py
>  S3_FIELDS = ["bucket", "object_key", "domain", "tenant", "user", "md5", "event_name"]
Is there an easy way to make this a superset of `REQUIRED_S3_FIELDS`?

2021-03-08 16:31 UTC, merged